# Generated by Django 3.2.8 on 2021-12-21 19:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('legacy', '0001_initial'), ('legacy', '0002_auto_20211126_1628'), ('legacy', '0003_auto_20211130_1659'), ('legacy', '0004_auto_20211130_1714'), ('legacy', '0005_auto_20211130_1751'), ('legacy', '0006_auto_20211202_1528'), ('legacy', '0007_quiz_g_url'), ('legacy', '0008_alter_module_index'), ('legacy', '0009_alter_trio_quiz'), ('legacy', '0010_auto_20211220_1437')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('img', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='legacy.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=254, upload_to='legacy/classes/')),
                ('video', models.URLField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trios', to='legacy.module')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trios', to='legacy.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='legacy.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='legacy.question')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='legacy.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_quizes', to=settings.AUTH_USER_MODEL)),
                ('score', models.ManyToManyField(related_name='answered', to='legacy.Answer')),
            ],
            options={
                'verbose_name_plural': 'UserQuizes',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ManyToManyField(related_name='quizes', through='legacy.UserQuiz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserTrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=3)),
                ('trio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.trio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserTrios',
            },
        ),
        migrations.AddField(
            model_name='trio',
            name='user',
            field=models.ManyToManyField(related_name='trios', through='legacy.UserTrio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trio',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trios', to='legacy.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='g_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trio',
            name='quiz',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trio',
            name='file',
            field=models.CharField(max_length=200),
        ),
    ]
