# Generated by Django 3.2.8 on 2021-12-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0001_squashed_0010_auto_20211220_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='trio',
            name='file_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
