# Generated by Django 3.2.8 on 2021-12-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_trio_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.URLField(),
        ),
    ]
