# Generated by Django 3.2.8 on 2021-11-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_auto_20211126_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquiz',
            options={'verbose_name_plural': 'UserQuizes'},
        ),
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
