# Generated by Django 3.2.8 on 2021-12-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0003_alter_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.URLField(max_length=500),
        ),
    ]
