# Generated by Django 3.2.8 on 2021-11-30 22:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy', '0004_auto_20211130_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ManyToManyField(related_name='quizes', through='legacy.UserQuiz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserTrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=3)),
                ('trio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.trio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trio',
            name='user',
            field=models.ManyToManyField(related_name='trios', through='legacy.UserTrio', to=settings.AUTH_USER_MODEL),
        ),
    ]
