# Generated by Django 3.2.8 on 2021-12-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
      ('legacy', '0005_auto_20211130_1751'),
  ]

  operations = [
      migrations.AlterModelOptions(
          name='usertrio',
          options={'verbose_name_plural': 'UserTrios'},
      ),
      migrations.AlterField(
          model_name='course',
          name='img',
          field=models.ImageField(upload_to='legacy/courses'),
      ),
      migrations.AlterField(
          model_name='trio',
          name='quiz',
          field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trios', to='legacy.quiz'),
      ),
  ]
