# Generated by Django 3.2.8 on 2021-12-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0006_auto_20211202_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='g_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
