# Generated by Django 3.2.8 on 2021-12-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0007_quiz_g_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='index',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
