# Generated by Django 3.2.8 on 2021-12-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0008_alter_module_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trio',
            name='quiz',
            field=models.URLField(blank=True, null=True),
        ),
    ]
