# Generated by Django 3.2.8 on 2021-12-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0009_alter_trio_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='trio',
            name='file',
            field=models.CharField(max_length=200),
        ),
    ]
