# Generated by Django 3.2.8 on 2021-11-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Si'), (0, 'No')], default=0),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
