# Generated by Django 3.2.8 on 2021-11-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cme', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('module', 'type')},
        ),
    ]
