# Generated by Django 3.2.8 on 2021-12-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme', '0001_squashed_0003_bussines_cme_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussines',
            name='legacy_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bussines',
            name='training_access',
            field=models.BooleanField(default=False),
        ),
    ]
