# Generated by Django 3.2.8 on 2021-11-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme', '0002_auto_20211108_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(default=None, max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
