# Generated by Django 3.2.8 on 2021-11-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme', '0002_alter_survey_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussines',
            name='cme_access',
            field=models.BooleanField(default=False),
        ),
    ]
