# Generated by Django 3.2.8 on 2021-11-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cme', '0003_module_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='cme.survey')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='cme.block'),
            preserve_default=False,
        ),
    ]
