# Generated by Django 3.2.8 on 2021-11-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme', '0004_auto_20211109_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.SmallIntegerField(choices=[(4, 'Si'), (0, 'No'), (-1, 'Indefinido')], default=-1),
        ),
    ]
