# Generated by Django 3.2.8 on 2021-11-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cme', '0006_alter_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
    ]
