# Generated by Django 3.2.8 on 2021-12-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20211221_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FILE'), (2, 'VIDEO')], default=2),
            preserve_default=False,
        ),
    ]
