# Generated by Django 3.2.8 on 2021-12-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_file_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='type',
            new_name='file_type',
        ),
    ]
