# Generated by Django 3.2.8 on 2021-12-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_rename_type_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='index',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
