# Generated by Django 3.2.8 on 2021-12-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_module_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.URLField(),
        ),
    ]
